format = """
$directory$git_branch
$shell$character"""

[directory]
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[ğŸ£](bold green)"
error_symbol   = "[ğŸ’¥](bold red)"

[cmd_duration]
disabled = true

[package]
disabled = true
