format = """
[â”Œâ”€â”€ ](bold green)$directory$git_branch$git_state$git_status
[â””â”€](bold green)$character"""

[directory]
fish_style_pwd_dir_length = 1

[character]
#success_symbol = "[â–¶](bold green)"
#error_symbol   = "[â–¶](bold red)"
success_symbol = "[ðŸ‘‰](bold green)"
error_symbol   = "[ðŸ–•](bold red)"

[cmd_duration]
disabled = true

[package]
disabled = true

[git_branch]
symbol = ""

[git_commit]
tag_symbol = "tag "

[git_status]
ahead = "â†‘"
behind = "â†“"
renamed = "~"
deleted = "%"
diverged = "@"
